version: "3.7"

services:
  name:
    image: arrowknee/dfs
    build: .
    environment:
      DFS_NODE_CLASS: name_node.NameNode
    ports:
      - 8180:8180
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
    restart: always

  data:
    image: arrowknee/dfs
    build: .
    environment:
      DFS_NODE_CLASS: data_node.DataNode
      DFS_PORT: '8181'
      DFS_PUBLIC_URL: "http://${DATA_HOST}:8181/"
      DFS_NAMENODE_URL: 'http://name:8180/'
    ports:
      - 8181:8181
    deploy:
      mode: global
    restart: always

